let title = "Yoga skunk";
console.log(typeof title);
let screens = '("Простые, Сложные, Интерактивные")';
console.log(screens.length);
console.log(screens.toLowerCase());
console.log(screens.split(", "));
let screenPrice = "Стоимость вёрскти экраснов " + 15000 + " рублей";
console.log(screenPrice);
let rollback = 10;
console.log("Откат посреднику за работу " + 10000 * (10 / 100) + " рублей");
let fullPrice = "Стоимость разработки сайта " + 100000 + " рублей";
console.log(typeof fullPrice);
console.log(fullPrice);
let adaptive = true;
console.log(typeof adaptive);